spring:
  datasource:
    url: ${DATABASE_URL}
    username: ${PGUSER}
    password: ${PGPASSWORD}
    driver-class-name: org.postgresql.Driver

  flyway:
    enabled: true
    baseline-on-migrate: true
    validate-on-migrate: false
  freemarker:
    expose-request-attributes: true
Server:
  error:
    include-message: always