spring:
  datasource:
    url: ${db-url}
    username: ${username}
    password: ${password}
    driver-class-name: org.postgresql.Driver

  freemarker:
    expose-request-attributes=true:

  flyway:
    enabled: true
    baseline-on-migrate: true
    validate-on-migrate: false
