spring:
  datasource:
    url: ${DATABASE_URL}
    username: ${PGUSER}
    password: ${PGPASSWORD}
    driver-class-name: org.postgresql.Driver

freemarker:
  expose-request-attributes=true:

flyway:
  enabled: true
  baseline-on-migrate: true
  validate-on-migrate: false
Server:
  error:
    include-message: always