INSERT INTO public.resources (id, name, subcategorie_id) VALUES (1, '3-Band Lite Cummerbund', 1);
INSERT INTO public.resources (id, name, subcategorie_id) VALUES (3, 'Precision AVS Plate Carrier', 1);
INSERT INTO public.resources (id, name, subcategorie_id) VALUES (4, 'battle Рlate Сarrier Vest Hidden Type UARM', 1);
INSERT INTO public.resources (id, name, subcategorie_id) VALUES (2, 'Seals Floating Harness', 1);
INSERT INTO public.resources (id, name, subcategorie_id) VALUES (5, 'Body Armour T-shirt UARM', 2);
INSERT INTO public.resources (id, name, subcategorie_id) VALUES (6, 'Body Armour CIT UARMPrecision LVS Overt Cover', 2);
INSERT INTO public.resources (id, name, subcategorie_id) VALUES (7, ' LVS Overt Cover Mag Pouch', 2);
INSERT INTO public.resources (id, name, subcategorie_id) VALUES (8, 'Medium Single Plate', 3);
INSERT INTO public.resources (id, name, subcategorie_id) VALUES (9, 'SAPI Plate – Large', 3);
INSERT INTO public.resources (id, name, subcategorie_id) VALUES (10, 'SAPI Plate – X-Large', 3);
INSERT INTO public.resources (id, name, subcategorie_id) VALUES (11, 'Ballistic Panels for Vertx', 3);
INSERT INTO public.resources (id, name, subcategorie_id) VALUES (12, 'helmet visualized for Ops-Core', 4);
INSERT INTO public.resources (id, name, subcategorie_id) VALUES (13, 'FAST High Cut Helmet', 4);
INSERT INTO public.resources (id, name, subcategorie_id) VALUES (14, ' ACH Ballistic Helmet', 4);
INSERT INTO public.resources (id, name, subcategorie_id) VALUES (15, 'Night Vision Goggles ', 5);
INSERT INTO public.resources (id, name, subcategorie_id) VALUES (16, 'Night Vision Monocular', 5);
INSERT INTO public.resources (id, name, subcategorie_id) VALUES (17, 'Night Vision Binoculars', 5);
INSERT INTO public.resources (id, name, subcategorie_id) VALUES (18, 'Clip-on Thermal ', 6);
INSERT INTO public.resources (id, name, subcategorie_id) VALUES (19, 'Thermal Imaging Sight', 6);
INSERT INTO public.resources (id, name, subcategorie_id) VALUES (20, 'Mini Thermal Monocular', 6);
INSERT INTO public.resources (id, name, subcategorie_id) VALUES (21, 'Warm Thermal Underwear', 7);
INSERT INTO public.resources (id, name, subcategorie_id) VALUES (22, 'Pants', 7);
INSERT INTO public.resources (id, name, subcategorie_id) VALUES (23, 'Shirt', 7);
INSERT INTO public.resources (id, name, subcategorie_id) VALUES (24, 'Windshirt ', 7);
INSERT INTO public.resources (id, name, subcategorie_id) VALUES (25, 'Camo clothes', 7);
INSERT INTO public.resources (id, name, subcategorie_id) VALUES (26, 'Knee Pads Inserts ', 8);
INSERT INTO public.resources (id, name, subcategorie_id) VALUES (27, 'Combat Knee Pads', 8);
INSERT INTO public.resources (id, name, subcategorie_id) VALUES (28, 'Tactical Belt', 9);
INSERT INTO public.resources (id, name, subcategorie_id) VALUES (29, 'Paratrooper Belt ', 9);
INSERT INTO public.resources (id, name, subcategorie_id) VALUES (30, 'Safety belt', 9);
INSERT INTO public.resources (id, name, subcategorie_id) VALUES (31, 'Mountain Combat Boots ', 10);
INSERT INTO public.resources (id, name, subcategorie_id) VALUES (32, 'Hot Weather Combat Hiker Boots', 10);
INSERT INTO public.resources (id, name, subcategorie_id) VALUES (33, 'Lace Desert Boots', 10);
INSERT INTO public.resources (id, name, subcategorie_id) VALUES (34, 'Field Boots MK.2 ', 11);
INSERT INTO public.resources (id, name, subcategorie_id) VALUES (35, 'Navy Blue Sport Shoes', 11);
INSERT INTO public.resources (id, name, subcategorie_id) VALUES (36, 'Surefire M952V IR LED WeaponLight', 12);
INSERT INTO public.resources (id, name, subcategorie_id) VALUES (37, 'LAD-22 TG Laser Module', 12);
INSERT INTO public.resources (id, name, subcategorie_id) VALUES (38, 'Surefire M910a Tactical Light', 12);
INSERT INTO public.resources (id, name, subcategorie_id) VALUES (39, '3x Afocal Lens Magnifer ', 13);
INSERT INTO public.resources (id, name, subcategorie_id) VALUES (40, 'Micro H-1 2МОА Weaver ', 13);
INSERT INTO public.resources (id, name, subcategorie_id) VALUES (41, 'G23.FTS Magnifier', 13);
INSERT INTO public.resources (id, name, subcategorie_id) VALUES (42, 'MSA Sordin Supreme headband', 14);
INSERT INTO public.resources (id, name, subcategorie_id) VALUES (43, 'Liberator II Neckband', 14);
INSERT INTO public.resources (id, name, subcategorie_id) VALUES (44, 'Tactical 6S Earmuffs', 15);
INSERT INTO public.resources (id, name, subcategorie_id) VALUES (45, 'LOF Passive Earmuff', 15);
INSERT INTO public.resources (id, name, subcategorie_id) VALUES (46, 'Baofeng UV-5R two-way radio', 16);
INSERT INTO public.resources (id, name, subcategorie_id) VALUES (47, 'Motorola DP3441E UHF', 16);
INSERT INTO public.resources (id, name, subcategorie_id) VALUES (48, 'Thales AN/PRC-148 Radio housing', 16);
