<html lang="en">
<head>
    <title>Profile</title>
    <link rel="stylesheet" href="css/bootstrap.min.css">
    <meta name="theme-color" content="#7952b3">
    <style>
        body {
            background-image: url('/images/bg.jpg');
            background-repeat: center center fixed;
            background-size: 100%;
        }
        #footer {
            position: absolute;
            bottom: 0;
            width: 100%;
        }
    </style>
    <link href="css/headers.css" rel="stylesheet">
    <link href="css/footers.css" rel="stylesheet">
    <link href="css/grid.css" rel="stylesheet">
    <link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png">
    <link rel="icon" type="image/png" sizes="96x96" href="/favicon-96x96.png">
    <link rel="icon" type="image/png" sizes="16x16" href="/favicon-16x16.png">
</head>

<body class="text-center">
<#include "header.ftlh">
<div id="footer">
<#include "footer.ftlh">
</div>
</body>
</html>